language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
install:
  - pip install tox
script:
  - tox
#deploy:
#  provider: azure_web_apps              # consider example as azure_web_apps
#  username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
#  password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
#  site: azure_deployment_sitename       # If AZURE_WA_SITE isn't set
#  slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set
notifications:
  email:
    recipients:
      - rakesh.cloud12@gmail.com
      - other_team_member@example.com
    on_success: never # default: change
    on_failure: always # default: always