---
swagger: "2.0"
info:
  description: "pymodules project with Flask and Connexion"
  version: "1.0.0"
  title: "pymodules Connexion example"
  contact:
    email: "rakesh.cloud12@gmail.com"
host: "0.0.0.0:8082"
basePath: "/v2/basic"
tags:
  - name: "alive"
    description: "Keepalive"
schemes:
  - "http"
produces:
  - "application/json"
consumes:
  - "application/json"
paths:
  /ping:
    get:
      tags:
        - "alive"
      summary: "Api keepalive"
      description: "Api keepalive"
      operationId: "is_alive"
      parameters: []
      responses:
        200:
          description: "is alive"
      x-swagger-router-controller: "basic.controllers.alive_controller"